### ISSUE TITLE
Using middleware to validate requests before the action

### ISSUE THREAD

**Issue by phudv96** [phudv96/Intern-Projects#4]
Overall is ok but we still need a middleware for all request API endpoints to ensure data is correct.
For example:
```
const createTask = async (req,res)=>{
    try{
    const task = await Task.create(req.body)
    res.status(201).json({task})
    } catch (error){
        res.status(500).json({msg: error})
    }
}
```
1. we need to add a check on middleware that the format of data (req.body) is correct after going through create task action.
2. please check all other functions as well.

**Comment by Ikariius** [comment]
I'm afraid I'm not grasping this issue yet, can you please explain further ?

In the controller.js, we extracted a defined schema model. The data extracted from the post request (and other requests alike) is then compared to the defined schema model to make sure it's in the right format. 

In theory, the format of the request needs to be correct otherwise an error will be thrown. 

Thank you for your time.
